name: Write prerelease comment

on:
  workflow_run:
    workflows: ["Create Pull Request Prerelease"]
    types:
      - completed

jobs:
  comment:
    if: ${{ github.repository_owner == 'cloudflare' }}
    runs-on: ubuntu-latest
    name: Write comment to the PR
    steps:
      - name: "Put PR and workflow ID on the environment"
        run: node .github/extract-pr-and-workflow-id.js

      - name: "Comment on PR with Link"
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ env.WORKFLOW_RUN_PR }}
          message: |
            A wrangler prerelease is available for testing. You can install it in your project with:

            ```sh
            npm install --save-dev https://prerelease-registry.developers.workers.dev/runs/${{ env.WORKFLOW_RUN_ID }}/wrangler
            ```

            Or you can try developing a worker directly with:
            ```sh
            npx https://prerelease-registry.developers.workers.dev/runs/${{ env.WORKFLOW_RUN_ID }}/wrangler dev path/to/script.js
            ```
